# Permalinks
permalink:        /post/:title.html

# Setup
url:              https://www.blogspace.gq
img_url:          https://infp.github.io/images

# Valine评论系统开关
# Valine.
# You can get your appid and appkey from https://leancloud.app
# more info please open https://valine.js.org
valine:
  enable: true
  appid:  zeRH0GG4bllparoqYJnC6X2b-gzGzoHsz # your leancloud app id
  appkey: IfblmRnOq8oaaA0wJ7YgMi8F # your leancloud app key
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: true # Verification code
  placeholder: 非Github帐号登录用户，在此处留言 # comment box placeholder
  avatar:   # gravatar style
  guest_info: 昵称,邮件,网址 # custom comment header
  pageSize: 10 # pagination size
  # path: window.location.pathname

# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            '一袖南烟顾的博客'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  分类：[IT](/it/) ··· [电影](/movie/) ··· [生活](/life/) ··· [全部](/)


# Google Analytics tracking ID
# TODO: 如果使用本主题，请务必替换此处的 Google 统计代码，否则你的站点将无法获得统计数据
analytics:        'UA-159417340-1'

# Fallback image and color if not overwritten for tag or post
image:            /public/images/hedin.jpg
color:            '#dc322f'

author:
  name:           '一袖南烟顾'
  email:          2826407926@qq.com
  github:         gqd000
#  linkedin:       https://github.com/gqd000
  email:       2826407926@qq.com
  photo:          /public/images/cat.jpg


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是一袖南烟顾，热爱电脑技术，喜欢与人交流分享开源思想和 IT 技术（其实很菜）。如果你觉得本文不错，请多多支持。


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
