# Permalinks
permalink:        /post/:title.html

# Setup
url:              https://www.blogspace.gq
img_url:          https://infp.github.io/images


# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            '一袖南烟顾'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  分类：[IT](/it/) ··· [电影](/movie/) ··· [生活](/life/) ··· [全部](/)


# Google Analytics tracking ID
# TODO: 如果使用本主题，请务必替换此处的 Google 统计代码，否则你的站点将无法获得统计数据
# analytics:        'UA-159417340-1'

baidu-analysis: xxxxxxxxxxxxxxxxxxxxxxxxxxx


# Fallback image and color if not overwritten for tag or post
image:            /public/images/hedin.jpg
color:            '#dc322f'

author:
  name:           '一袖南烟顾'
  email:          2826407926@qq.com
  github:         gqd000
#  linkedin:       https://github.com/gqd000
  email:       2826407926@qq.com
  photo:          /public/images/cat.jpg


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    # 一袖南烟顾     
    ##  淡泊以明志 ，宁静以致远。


compress_html:
  clippings:      all
  comment:      <--","-->
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
